[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  base = "apps/portfolio"
  publish = "/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run generate"
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200